---
title: "Bridge Fight Club 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{css center, echo = FALSE}
h1, h2, h3 {
  text-align: center;
}
```

```{r funcs, echo = FALSE, warning = FALSE, message = FALSE, fig.dim=c(10,10)}
library(dplyr)
library(ggplot2)
library(kableExtra)
library(readr)

## Teams
blue <- c("nohk",
                 "pjmingola",
                 "Rasern",
                 "ye17",
                 "zimman")
red <- c("MikeyAK",
                 "Modigliana",
                 "mounteban",
                 "dcavalier",
                 "njjj")
orange <- c("barissalt",
                 "biggeek",
                 "bzl11",
                 "C3Crackers",
                 "Charlie397")
purple <- c("GaborF",
                 "gamma57309",
                 "humper",
                 "marksmanma",
                 "Mayjester")
yellow <- c("rustysnow",
                 "ShinyB",
                 "v8mama",
                 "Vulturon",
                 "wyleia")
green <- c("coolbeans",
                 "cosmok",
                 "curlingguy",
                 "Duality",
                 "Forrest_")

player.list <- c(blue, green, orange, purple, red, yellow)


indivpts <- function(results){
  results$IndPtsP1 <- 0
  for(i in 1:nrow(results)){
    if(results$Forfeit[i] == "Y"){
      results$IndPtsP1[i] <- 3
    } else {
      ifelse(results$PosIMPsP1[i] == results$NegIMPsP1[i], 
           results$IndPtsP1[i] <- 1,
           ifelse(results$PosIMPsP1[i] > results$NegIMPsP1[i],
                  results$IndPtsP1[i] <- 3,
                  results$IndPtsP1[i] <- 0))
    }
  }
  return(results)
}

p2results <- function(results){
  if(results[6] == "Y"){
    p2r <- c(results[2],
             results[1],
             0,
             results[5],
             results[4],
             "Y",
             results[8],
             results[7],
             0)
  } else {
    indpts <- ifelse(results[5] == results[4], 1, 
                     ifelse(results[5] > results[4], 3, 0))
    p2r <- c(results[2],
             results[1],
             6 - results[3],
             results[5],
             results[4],
             "N",
             results[8],
             results[7],
             indpts)
  }
  return(p2r)
}

getoutput <- function(results, out) {
  starting.out <- out
  for(i in 1:nrow(results)){
    starting.out[starting.out$Player1 == results$Player1[i] &
                 starting.out$Player2 == results$Player2[i],] <- results[i,]
    starting.out[starting.out$Player1 == results$Player2[i] &
                   starting.out$Player2 == results$Player1[i],] <- p2results(results[i,])
  }
  starting.out$TeamPtsP1 <- as.numeric(starting.out$TeamPtsP1)
  starting.out$PosIMPsP1 <- as.numeric(starting.out$PosIMPsP1)
  starting.out$NegIMPsP1 <- as.numeric(starting.out$NegIMPsP1)
  return(starting.out)
}

makeplots <- function(output) {
  output$IndPtsP1 <- as.factor(output$IndPtsP1)
  
  team.colors <- c(rep("#3498db", 5),
                 rep("#1f8b4c", 5),
                 rep("#f1c40f", 5),
                 rep("#71368a", 5),
                 rep("red", 5),
                 rep("orange", 5))

  indpts <- ggplot(output, (aes(x = Player2, y = Player1, fill = IndPtsP1))) +
    geom_tile(color = "white", size = .25) +
    geom_text(data = output[!is.na(output$IndPtsP1),], aes(label = IndPtsP1), color = "white") + theme_bw() +
    theme(text = element_text(size = 18),
          axis.text.x = element_text(angle = 90, hjust = 1, color = team.colors),
          axis.text.y = element_text(color = team.colors),
          plot.title = element_text(hjust = 0.5, face = "bold"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank()) +
    xlab("Opponent") + ylab("You") +
    ggtitle("Individual Points Matrix") +
    scale_fill_manual(values = c("#2E382E", "#72A1E5", "#9883E5"),
                      name = "Points",
                      labels = c("Loss", "Tie", "Win"),
                      na.value = "white",
                      na.translate = FALSE)
  
  posimps <- ggplot(output, (aes(x = Player2, y = Player1, fill = PosIMPsP1))) +
    geom_tile(color = "white", size = .25) +
    geom_text(data = output[!is.na(output$PosIMPsP1),], aes(label = PosIMPsP1), color = "white") + theme_bw() +
    theme(text = element_text(size = 18),
          axis.text.x = element_text(angle = 90, hjust = 1, color = team.colors),
          axis.text.y = element_text(color = team.colors),
          plot.title = element_text(hjust = 0.5, face = "bold"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank()) +
    xlab("Opponent") + ylab("You") +
    ggtitle("Individual Positive IMPs Matrix") +
    scale_fill_gradient(low = "blue", high = "red", na.value = "white", name = "Positive IMPs")

  negimps <- ggplot(output, (aes(x = Player2, y = Player1, fill = NegIMPsP1))) +
    geom_tile(color = "white", size = .25) +
    geom_text(data = output[!is.na(output$NegIMPsP1),], aes(label = NegIMPsP1), color = "white") + theme_bw() +
    theme(text = element_text(size = 18),
          axis.text.x = element_text(angle = 90, hjust = 1, color = team.colors),
          axis.text.y = element_text(color = team.colors),
          plot.title = element_text(hjust = 0.5, face = "bold"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank()) +
    xlab("Opponent") + ylab("You") +
    ggtitle("Individual Negative IMPs Matrix") +
    scale_fill_gradient(low = "blue", high = "red", na.value = "white", name = "Negative IMPs")
  
  teampts <- ggplot(output, (aes(x = Player2, y = Player1, fill = TeamPtsP1))) +
    geom_tile(color = "white", size = .25) +
    geom_text(data = output[!is.na(output$TeamPtsP1),], aes(label = TeamPtsP1), color = "white") + theme_bw() +
    theme(text = element_text(size = 18),
          axis.text.x = element_text(angle = 90, hjust = 1, color = team.colors),
          axis.text.y = element_text(color = team.colors),
          plot.title = element_text(hjust = 0.5, face = "bold"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank()) +
    xlab("Opponent") + ylab("You") +
    ggtitle("Team Points Matrix") +
    scale_fill_gradient(low = "blue", high = "red", na.value = "white", name = "Team Points")
  
  plot.list <- list(indpts, posimps, negimps, teampts)
}

summaryindiv <- function(output){
  indiv <- output %>% group_by(Player1) %>% summarise("Individual Points" = sum(IndPtsP1, na.rm = TRUE),
                                                      "Team Points" = sum(TeamPtsP1, na.rm = TRUE))
  colnames(indiv)[1] <- c("Player")
  
  indiv <- indiv[order(rowSums(indiv[,2:3]), decreasing = TRUE),]
  
  return(indiv)
}

summaryteam <- function(indiv) {
  bluepts <- sum(indiv$`Team Points`[indiv$Player %in% blue])
  greenpts <- sum(indiv$`Team Points`[indiv$Player %in% green])
  orangepts <- sum(indiv$`Team Points`[indiv$Player %in% orange])
  redpts <- sum(indiv$`Team Points`[indiv$Player %in% red])
  purplepts <- sum(indiv$`Team Points`[indiv$Player %in% purple])
  yellowpts <- sum(indiv$`Team Points`[indiv$Player %in% yellow])

  team <- data.frame(Team = c("Blue", "Green", "Orange", "Yellow", "Red", "Purple"),
                     Points = c(bluepts, greenpts, orangepts, yellowpts, redpts, purplepts))
  
  team <- team[order(team$Points, decreasing = TRUE),]
  
  return(team)
}

benched <- function(output){
  for(i in 1:nrow(output)){
    if(output$BenchP1[i] == "Y"){
      output$TeamPtsP1[i] <- 0
    }
  }
  return(output)
}


importdata <- function(path){
  data <- read_csv(path, skip = 1)
  data <- data[,c(1,6,3,2,7,8,4,9)]
  colnames(data) <- c("Player1", "Player2","TeamPtsP1","PosIMPsP1",
                      "NegIMPsP1","Forfeit","BenchP1","BenchP2")
  return(data)
}

starting.out <- expand.grid(player.list, player.list)
colnames(starting.out) <- c("Player1", "Player2")
starting.out <- starting.out[starting.out$Player1 != starting.out$Player2,]
starting.out$TeamPtsP1 <- rep(NA, nrow(starting.out))
starting.out$PosIMPsP1 <- rep(NA, nrow(starting.out))
starting.out$NegIMPsP1 <- rep(NA, nrow(starting.out))
starting.out$Forfeit <- rep("N", nrow(starting.out))
starting.out$BenchP1 <- rep("N", nrow(starting.out))
starting.out$BenchP2 <- rep("N", nrow(starting.out))
starting.out$IndPtsP1 <- rep(NA, nrow(starting.out))


# results <- data.frame(Player1 = c("gamma57309","wyleia","dcavalier"),
#                       Player2 = c("wyleia", "dcavalier", "gamma57309"),
#                       TeamPtsP1 = as.numeric(c(4,4,4)),
#                       PosIMPsP1 = as.numeric(c(10,4,10)),
#                       NegIMPsP1 = as.numeric(c(4,4,4)),
#                       Forfeit = c("N", "N", "N"),
#                       stringsAsFactors = FALSE)

results <- importdata("~/Downloads/BFC2 Scoresheet - Sheet1 (1).csv")

results <- indivpts(results)
big.output <- getoutput(results, starting.out)
big.output2 <- benched(big.output)
plots <- makeplots(big.output2)
indiv.table <- summaryindiv(big.output2)
team.table <- summaryteam(indiv.table)
```

# Table Results {.tabset .tabset-fade .tabset-pills}

## Individual Results Summary

```{r sum, echo = FALSE, warning = FALSE, fig.dim=c(10,10)}

indiv.table %>% 
  kable("html") %>% 
  kable_styling(font_size = 18, full_width = F) %>%
  row_spec(which(indiv.table$Player %in% blue), color = "#3498db") %>%
  row_spec(which(indiv.table$Player %in% green), color = "#1f8b4c") %>%
  row_spec(which(indiv.table$Player %in% yellow), color = "#f1c40f") %>%
  row_spec(which(indiv.table$Player %in% purple), color = "#71368a") %>%
  row_spec(which(indiv.table$Player %in% red), color = "red") %>%
  row_spec(which(indiv.table$Player %in% orange), color = "orange") 
```

## Team Results Summary

```{r teamsum, echo = FALSE, warning = FALSE, fig.dim=c(10,10)}
team.table %>%
  kable("html", row.names = FALSE) %>%
  kable_styling(font_size = 18, full_width = F) %>%
  row_spec(which(team.table$Team == "Blue"), color = "#3498db") %>%
  row_spec(which(team.table$Team == "Green"), color = "#1f8b4c") %>%
  row_spec(which(team.table$Team == "Yellow"), color = "#f1c40f") %>%
  row_spec(which(team.table$Team == "Purple"), color = "#71368a") %>%
  row_spec(which(team.table$Team == "Red"), color = "red") %>%
  row_spec(which(team.table$Team == "Orange"), color = "orange")
```

# Matrix Results {.tabset .tabset-fade .tabset-pills}

## Individual Points Matrix

```{r indivmtx, echo=FALSE, warning=FALSE, fig.dim=c(10,10)}
print(plots[[1]])
```

## Team Points Matrix
```{r teampts, echo = FALSE, warning = FALSE, fig.dim=c(10,10)}
print(plots[[4]])
```

## Individual Positive IMPs Matrix
```{r indpos, echo = FALSE, warning = FALSE, fig.dim=c(10,10)}
print(plots[[2]])
```

## Individual Negative IMPs Matrix
```{r indneg, echo = FALSE, warning = FALSE, fig.dim=c(10,10)}
print(plots[[3]])
```